version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: employee-service:latest  
    build: ./    
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres